name: home_ui
description: "두유톤 19팀 - 친환경 소비 앱 (Lumina Nature)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  go_router: ^14.6.2
  material_symbols_icons: ^4.2799.0
  camera: ^0.11.0+2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
